select l.del_header_id,
       l.rowno line_num,
       l.item_number,
       l.item_desc,
       l.unit_of_measure_tl,
       l.quantity,
       l.delivery_count,
       l.remark
  from (SELECT t.amount,
               t.amount_received,
               t.approved_flag,
               t.attribute1,
               t.attribute2,
               t.attribute3,
               t.attribute6,
               t.cancel_flag,
               t.category_id,
               t.contract_id,
               t.contract_name,
               t.currency_code,
               t.item_desc,
               t.item_id,
               t.item_number,
               t.line_num,
               t.need_by_date,
               t.order_amount,
               t.order_quantity,
               t.percentage_rate,
               t.po_header_id,
               t.po_line_id,
               t.project_block_id,
               t.project_block_name,
               t.project_id,
               t.project_name,
               t.promised_date,
               t.quantity,
               t.quantity_accepted,
               t.quantity_billed,
               t.quantity_cancelled,
               t.quantity_received,
               t.quantity_rejected,
               t.ramark,
               t.tax_rate_amount,
               t.tax_rate_code,
               t.unit_meas_lookup_code,
               t.unit_of_measure,
               t.unit_of_measure_tl,
               t.unit_price,
               t.line_location_id,
               t.del_header_id,
               t.delivery_lines_id,
               t.delivery_count,
               t.remark,
               t.quantityHaveDelivery,
               dense_rank() over(PARTITION BY t.del_header_id ORDER BY t.delivery_lines_id) rowno
          FROM cux_delivery_lines_v t
         WHERE 1 = 1
           and t.del_header_id = 6101) l
/* WHERE l.rowno > :2
AND l.rowno <= :3*/
